namespace types
{
	/// <summary>
	/// @CSharpLua.Ignore
	/// </summary>
	public enum BlendFunction
	{
		BLEND_ZERO = 0,
		BLEND_ONE = 1,
		BLEND_SRC_COLOR = 2,
		BLEND_ONE_MINUS_SRC_COLOR = 3,
		BLEND_DST_COLOR = 4,
		BLEND_ONE_MINUS_DST_COLOR = 5,
		BLEND_SRC_ALPHA = 6,
		BLEND_ONE_MINUS_SRC_ALPHA = 7,
		BLEND_DST_ALPHA = 8,
		BLEND_ONE_MINUS_DST_ALPHA = 9,
		BLEND_SRC_ALPHA_SATURATE = 10,
		BLEND_CONSTANT_COLOR = 11,
		BLEND_ONE_MINUS_CONSTANT_COLOR = 12,
		BLEND_CONSTANT_ALPHA = 13,
		BLEND_ONE_MINUS_CONSTANT_ALPHA = 14,
	}
}
