using System;
using lua;

namespace types
{
	/// <summary>
	/// </summary>
	public enum Easing
	{
		EASING_LINEAR = 0,
		EASING_INQUAD = 1,
		EASING_OUTQUAD = 2,
		EASING_INOUTQUAD = 3,
		EASING_OUTINQUAD = 4,
		EASING_INCUBIC = 5,
		EASING_OUTCUBIC = 6,
		EASING_INOUTCUBIC = 7,
		EASING_OUTINCUBIC = 8,
		EASING_INQUART = 9,
		EASING_OUTQUART = 10,
		EASING_INOUTQUART = 11,
		EASING_OUTINQUART = 12,
		EASING_INQUINT = 13,
		EASING_OUTQUINT = 14,
		EASING_INOUTQUINT = 15,
		EASING_OUTINQUINT = 16,
		EASING_INSINE = 17,
		EASING_OUTSINE = 18,
		EASING_INOUTSINE = 19,
		EASING_OUTINSINE = 20,
		EASING_INEXPO = 21,
		EASING_OUTEXPO = 22,
		EASING_INOUTEXPO = 23,
		EASING_OUTINEXPO = 24,
		EASING_INCIRC = 25,
		EASING_OUTCIRC = 26,
		EASING_INOUTCIRC = 27,
		EASING_OUTINCIRC = 28,
		EASING_INELASTIC = 29,
		EASING_OUTELASTIC = 30,
		EASING_INOUTELASTIC = 31,
		EASING_OUTINELASTIC = 32,
		EASING_INBACK = 33,
		EASING_OUTBACK = 34,
		EASING_INOUTBACK = 35,
		EASING_OUTINBACK = 36,
		EASING_INBOUNCE = 37,
		EASING_OUTBOUNCE = 38,
		EASING_INOUTBOUNCE = 39,
		EASING_OUTINBOUNCE = 40,
	}
}
